# sklearn - train_test_split

In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
#train_test_split?

Note: The input array into train_test_split can be lists, numpy arrays, pandas dataframe and scipy-sparse matrices

*arrays : 

sequence of indexables with same length / shape[0]
    
Allowed inputs are lists, numpy arrays, scipy-sparse
matrices or pandas dataframes.

### Generate Data

In [3]:
np.random.seed(42)
arr = np.random.randint(0,10,size=(10,2))
arr

array([[6, 3],
       [7, 4],
       [6, 9],
       [2, 6],
       [7, 4],
       [3, 7],
       [7, 2],
       [5, 4],
       [1, 7],
       [5, 1]])

In [4]:
X = arr[:,0]
X

array([6, 7, 6, 2, 7, 3, 7, 5, 1, 5])

In [5]:
y = arr[:,1]
y

array([3, 4, 9, 6, 4, 7, 2, 4, 7, 1])

### Apply train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Results

In [7]:
X_train

array([6, 5, 6, 5, 7, 2, 7])

In [8]:
y_train

array([3, 4, 9, 1, 4, 6, 2])

In [9]:
y_test

array([7, 4, 7])

In [10]:
y_train

array([3, 4, 9, 1, 4, 6, 2])